### ISSUE TITLE
Yearn 0 share withdraw bugfix

### ISSUE THREAD

**Issue by pvienhage** [element-fi/elf-contracts#211]
The yearn asset proxy has a small stability bug in the reserve withdraw function which may cause reverts when attempting to withdraw under some circumstances.  https://github.com/element-fi/elf-contracts/blob/main/contracts/YVaultAssetProxy.sol#L131 Should be edited to only call withdraw when the share value is nonzero.

**Comment by jrhea** [comment]
@pvienhage has this been addressed in v1.1?

**Comment by pvienhage** [comment]
Yes
